services:
  wiki:
    image: ghcr.io/requarks/wiki:2
    environment:
      DB_TYPE: postgres
      DB_HOST: rc1a-wn9ns0e2z746q217.mdb.yandexcloud.net
      DB_PORT: 6432
      DB_USER: wikiadmin
      DB_PASS: 
      DB_NAME: wiki
    restart: unless-stopped
    ports:
      - "80:3000"